name: Run Tests

on:
  push:
    branches: [ 2021 ]
  pull_request:
    branches: 
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
      with:
        submodules: 'recursive'    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.13.2
      with:
        version: 5.15.2
        modules: qtcharts
    - name: Install Cmake    
      run: |
          sudo apt-get update -y
          sudo apt-get install cmake -y
          cmake --version
          gcc --version    
    - name: lz4
      run: cmake -DLZ4_BUNDLED_MODE=ON  . && make
      working-directory: 3rdparty/lz4/build/cmake
    - name: qmake
      run: qmake
      working-directory: ./src
    - name: make
      run: make
      working-directory: ./src
